"""Central configuration for MediBot.

Everything tunable (paths, model names, retrieval sizes) lives here so the rest
of the code never hard-codes a path or a model id.
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[2]

load_dotenv(PROJECT_ROOT / ".env")

# The machine this was built on sits behind a TLS-intercepting proxy, so the
# system root store has to be merged into the CA bundle used by every HTTP
# client (pip, huggingface_hub, groq). certs/ca-bundle.pem is generated by
# scripts/make_ca_bundle.ps1 and is optional on machines without interception.
_CA_BUNDLE = PROJECT_ROOT / "certs" / "ca-bundle.pem"
if _CA_BUNDLE.exists():
    for _var in ("SSL_CERT_FILE", "REQUESTS_CA_BUNDLE", "CURL_CA_BUNDLE"):
        os.environ.setdefault(_var, str(_CA_BUNDLE))

# --- Data -------------------------------------------------------------------
DATA_DIR = Path(os.getenv("MEDIBOT_DATA_DIR", str(PROJECT_ROOT / "mediassist_data")))
DB_PATH = Path(os.getenv("MEDIBOT_DB_PATH", str(DATA_DIR / "db" / "mediassist.db")))

STORAGE_DIR = Path(os.getenv("MEDIBOT_STORAGE_DIR", str(PROJECT_ROOT / "storage")))
QDRANT_PATH = STORAGE_DIR / "qdrant"
CHUNK_CACHE_PATH = STORAGE_DIR / "chunks.jsonl"
QDRANT_COLLECTION = "medibot_docs"

# --- Models -----------------------------------------------------------------
DENSE_MODEL = os.getenv("MEDIBOT_DENSE_MODEL", "BAAI/bge-small-en-v1.5")
DENSE_DIM = int(os.getenv("MEDIBOT_DENSE_DIM", "384"))
SPARSE_MODEL = os.getenv("MEDIBOT_SPARSE_MODEL", "Qdrant/bm25")
RERANK_MODEL = os.getenv("MEDIBOT_RERANK_MODEL", "Xenova/ms-marco-MiniLM-L-6-v2")
CHUNK_TOKENIZER = os.getenv("MEDIBOT_CHUNK_TOKENIZER", DENSE_MODEL)
MAX_CHUNK_TOKENS = int(os.getenv("MEDIBOT_MAX_CHUNK_TOKENS", "512"))

# --- Retrieval sizes --------------------------------------------------------
# Hybrid retrieval casts a wide net, the cross-encoder narrows it down.
HYBRID_CANDIDATES = int(os.getenv("MEDIBOT_HYBRID_CANDIDATES", "10"))
PREFETCH_LIMIT = int(os.getenv("MEDIBOT_PREFETCH_LIMIT", "20"))
RERANK_TOP_K = int(os.getenv("MEDIBOT_RERANK_TOP_K", "3"))
# Below this cross-encoder score the best chunk is treated as "not really an
# answer", which lets MediBot say "I don't know" instead of hallucinating.
MIN_RERANK_SCORE = float(os.getenv("MEDIBOT_MIN_RERANK_SCORE", "-6.0"))

# --- LLM --------------------------------------------------------------------
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-20b")

# --- Auth -------------------------------------------------------------------
SECRET_KEY = os.getenv("MEDIBOT_SECRET_KEY", "medibot-dev-secret-change-me")
TOKEN_TTL_SECONDS = int(os.getenv("MEDIBOT_TOKEN_TTL_SECONDS", str(8 * 3600)))

CORS_ORIGINS = [
    o.strip()
    for o in os.getenv("MEDIBOT_CORS_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000").split(",")
    if o.strip()
]
