"""Central configuration for MediBot.

Everything tunable (paths, model names, retrieval sizes) lives here so the rest
of the code never hard-codes a path or a model id.
"""
from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[2]

load_dotenv(PROJECT_ROOT / ".env")

# The machine this was built on sits behind a TLS-intercepting proxy, so the
# system root store has to be merged into the CA bundle used by every HTTP
# client (pip, huggingface_hub, groq). certs/ca-bundle.pem is generated by
# scripts/make_ca_bundle.ps1 and is optional on machines without interception.
_CA_BUNDLE = PROJECT_ROOT / "certs" / "ca-bundle.pem"
if _CA_BUNDLE.exists():
    for _var in ("SSL_CERT_FILE", "REQUESTS_CA_BUNDLE", "CURL_CA_BUNDLE"):
        os.environ.setdefault(_var, str(_CA_BUNDLE))

# --- Data -------------------------------------------------------------------
DATA_DIR = Path(os.getenv("MEDIBOT_DATA_DIR", str(PROJECT_ROOT / "mediassist_data")))
DB_PATH = Path(os.getenv("MEDIBOT_DB_PATH", str(DATA_DIR / "db" / "mediassist.db")))

STORAGE_DIR = Path(os.getenv("MEDIBOT_STORAGE_DIR", str(PROJECT_ROOT / "storage")))
QDRANT_PATH = STORAGE_DIR / "qdrant"
CHUNK_CACHE_PATH = STORAGE_DIR / "chunks.jsonl"
QDRANT_COLLECTION = "medibot_docs"

# --- Models -----------------------------------------------------------------
DENSE_MODEL = os.getenv("MEDIBOT_DENSE_MODEL", "BAAI/bge-small-en-v1.5")
DENSE_DIM = int(os.getenv("MEDIBOT_DENSE_DIM", "384"))
SPARSE_MODEL = os.getenv("MEDIBOT_SPARSE_MODEL", "Qdrant/bm25")
RERANK_MODEL = os.getenv("MEDIBOT_RERANK_MODEL", "Xenova/ms-marco-MiniLM-L-6-v2")
CHUNK_TOKENIZER = os.getenv("MEDIBOT_CHUNK_TOKENIZER", DENSE_MODEL)
MAX_CHUNK_TOKENS = int(os.getenv("MEDIBOT_MAX_CHUNK_TOKENS", "512"))

# --- Retrieval sizes --------------------------------------------------------
# Hybrid retrieval casts a wide net, the cross-encoder narrows it down.
HYBRID_CANDIDATES = int(os.getenv("MEDIBOT_HYBRID_CANDIDATES", "10"))
PREFETCH_LIMIT = int(os.getenv("MEDIBOT_PREFETCH_LIMIT", "20"))
RERANK_TOP_K = int(os.getenv("MEDIBOT_RERANK_TOP_K", "3"))
# Below this cross-encoder score the best chunk is treated as "not really an
# answer", which lets MediBot say "I don't know" instead of hallucinating.
MIN_RERANK_SCORE = float(os.getenv("MEDIBOT_MIN_RERANK_SCORE", "-6.0"))

# --- LLM --------------------------------------------------------------------
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")


def _flag(name: str, default: bool) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


# --- Guardrails -------------------------------------------------------------
# The input/output guardrail layer. Deterministic checks always run; the
# OpenEvals LLM judge only runs when they are inconclusive.
GUARDRAILS_ENABLED = _flag("MEDIBOT_GUARDRAILS_ENABLED", True)
GUARDRAIL_JUDGE_ENABLED = _flag("MEDIBOT_GUARDRAIL_JUDGE_ENABLED", True)
# A small, fast model is enough for a yes/no safety verdict.
GUARDRAIL_MODEL = os.getenv("MEDIBOT_GUARDRAIL_MODEL", "llama-3.1-8b-instant")
GUARDRAIL_JUDGE_TIMEOUT = float(os.getenv("MEDIBOT_GUARDRAIL_JUDGE_TIMEOUT", "12"))
# A malformed verdict ALWAYS blocks. This flag only covers the case where the
# judge cannot be reached at all (no key, network down): with it on, the
# deterministic verdict stands and the outage is logged at ERROR.
GUARDRAIL_FALLBACK_DETERMINISTIC = _flag("MEDIBOT_GUARDRAIL_FALLBACK_DETERMINISTIC", True)

# Optional AWS Bedrock Guardrails layer - inactive unless an id is configured.
BEDROCK_GUARDRAIL_ID = os.getenv("MEDIBOT_BEDROCK_GUARDRAIL_ID", "")
BEDROCK_GUARDRAIL_VERSION = os.getenv("MEDIBOT_BEDROCK_GUARDRAIL_VERSION", "DRAFT")
BEDROCK_REGION = os.getenv("MEDIBOT_BEDROCK_REGION", os.getenv("AWS_REGION", "ap-south-1"))

# --- Auth -------------------------------------------------------------------
SECRET_KEY = os.getenv("MEDIBOT_SECRET_KEY", "medibot-dev-secret-change-me")
TOKEN_TTL_SECONDS = int(os.getenv("MEDIBOT_TOKEN_TTL_SECONDS", str(8 * 3600)))

CORS_ORIGINS = [
    o.strip()
    for o in os.getenv("MEDIBOT_CORS_ORIGINS", "http://localhost:3000,http://127.0.0.1:3000").split(",")
    if o.strip()
]
